<?php

namespace AppBundle\Entity\Repository;

/**
 * DiscsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscsRepository extends \Doctrine\ORM\EntityRepository
{
}
