<?php

namespace AppBundle\Entity\Repository;

/**
 * SingersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SingersRepository extends \Doctrine\ORM\EntityRepository
{
}
